-- Populate products table with sample data for delivery tasks
-- This will ensure the delivery task form has products to select from

-- Insert sample products with proper structure for delivery tasks
INSERT INTO products (
  product_name,
  product_name_ar,
  product_code,
  stock_number,
  stock_number_ar,
  stock,
  main_group,
  sub_group,
  color,
  material,
  unit,
  description,
  description_ar,
  cost_price,
  selling_price,
  weight,
  dimensions,
  warehouses,
  is_active
) VALUES 
-- Industrial Steel Products
(
  'Steel Pipes 6 inch',
  'أنابيب حديدية 6 بوصة',
  'SP-006',
  'ST-001',
  'ST-001',
  150.00,
  'Steel Products',
  'Pipes',
  'Silver',
  'Carbon Steel',
  'pcs',
  'High quality steel pipes for industrial use',
  'أنابيب حديدية عالية الجودة للاستخدام الصناعي',
  25000.00,
  30000.00,
  15.5,
  '6x3000mm',
  'Main Warehouse',
  true
),
(
  'Steel Beams I-Beam',
  'كمرات حديدية',
  'SB-001',
  'ST-002',
  'ST-002',
  75.00,
  'Steel Products',
  'Structural',
  'Silver',
  'Carbon Steel',
  'pcs',
  'Heavy duty steel beams for construction',
  'كمرات حديدية ثقيلة للبناء',
  45000.00,
  55000.00,
  25.0,
  '200x100x3000mm',
  'Main Warehouse',
  true
),
(
  'Steel Sheets 2mm',
  'ألواح حديدية 2 مم',
  'SS-002',
  'ST-003',
  'ST-003',
  200.00,
  'Steel Products',
  'Sheets',
  'Silver',
  'Carbon Steel',
  'pcs',
  'Thin steel sheets for fabrication',
  'ألواح حديدية رقيقة للتشكيل',
  12000.00,
  15000.00,
  8.5,
  '1000x2000x2mm',
  'Main Warehouse',
  true
),

-- Aluminum Products
(
  'Aluminum Sheets 3mm',
  'ألواح ألمنيوم 3 مم',
  'AS-003',
  'AL-001',
  'AL-001',
  120.00,
  'Aluminum Products',
  'Sheets',
  'Silver',
  'Aluminum',
  'pcs',
  'Lightweight aluminum sheets',
  'ألواح ألمنيوم خفيفة الوزن',
  18000.00,
  22000.00,
  5.2,
  '1000x2000x3mm',
  'Main Warehouse',
  true
),
(
  'Aluminum Pipes 4 inch',
  'أنابيب ألمنيوم 4 بوصة',
  'AP-004',
  'AL-002',
  'AL-002',
  80.00,
  'Aluminum Products',
  'Pipes',
  'Silver',
  'Aluminum',
  'pcs',
  'Corrosion resistant aluminum pipes',
  'أنابيب ألمنيوم مقاومة للتآكل',
  22000.00,
  28000.00,
  12.0,
  '4x3000mm',
  'Main Warehouse',
  true
),

-- Plastic Products
(
  'PVC Pipes 2 inch',
  'أنابيب PVC 2 بوصة',
  'PP-002',
  'PL-001',
  'PL-001',
  300.00,
  'Plastic Products',
  'Pipes',
  'White',
  'PVC',
  'pcs',
  'Durable PVC pipes for plumbing',
  'أنابيب PVC متينة للسباكة',
  8000.00,
  12000.00,
  2.5,
  '2x3000mm',
  'Main Warehouse',
  true
),
(
  'HDPE Sheets 5mm',
  'ألواح HDPE 5 مم',
  'HS-005',
  'PL-002',
  'PL-002',
  100.00,
  'Plastic Products',
  'Sheets',
  'Blue',
  'HDPE',
  'pcs',
  'High density polyethylene sheets',
  'ألواح بولي إيثيلين عالي الكثافة',
  15000.00,
  20000.00,
  3.8,
  '1000x2000x5mm',
  'Main Warehouse',
  true
),

-- Electrical Components
(
  'Copper Wire 2.5mm',
  'سلك نحاسي 2.5 مم',
  'CW-025',
  'EL-001',
  'EL-001',
  500.00,
  'Electrical',
  'Wiring',
  'Brown',
  'Copper',
  'meters',
  'High quality copper electrical wire',
  'سلك كهربائي نحاسي عالي الجودة',
  25.00,
  35.00,
  0.5,
  '2.5mm²',
  'Main Warehouse',
  true
),
(
  'Electrical Conduit 20mm',
  'قناة كهربائية 20 مم',
  'EC-020',
  'EL-002',
  'EL-002',
  200.00,
  'Electrical',
  'Conduits',
  'Gray',
  'PVC',
  'meters',
  'Electrical conduit for cable protection',
  'قناة كهربائية لحماية الكابلات',
  15.00,
  25.00,
  0.8,
  '20mm diameter',
  'Main Warehouse',
  true
),

-- Tools and Equipment
(
  'Steel Wrenches Set',
  'مجموعة مفاتيح حديدية',
  'SW-SET',
  'TL-001',
  'TL-001',
  50.00,
  'Tools',
  'Hand Tools',
  'Black',
  'Steel',
  'set',
  'Professional steel wrench set',
  'مجموعة مفاتيح حديدية احترافية',
  45000.00,
  60000.00,
  2.0,
  'Various sizes',
  'Main Warehouse',
  true
),
(
  'Safety Helmets',
  'خوذات أمان',
  'SH-001',
  'SF-001',
  'SF-001',
  100.00,
  'Safety Equipment',
  'Head Protection',
  'Yellow',
  'ABS Plastic',
  'pcs',
  'Industrial safety helmets',
  'خوذات أمان صناعية',
  15000.00,
  25000.00,
  0.5,
  'One size fits all',
  'Main Warehouse',
  true
);

-- Verify the data was inserted
SELECT 
  id,
  product_name,
  product_code,
  stock,
  main_group,
  selling_price,
  is_active
FROM products 
WHERE is_active = true 
ORDER BY product_name;
