"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"

type Language = "en" | "ar"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
  isRTL: boolean
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations = {
  en: {
    // Auth
    "auth.login": "Login",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.signIn": "Sign In",
    "auth.selectRole": "Select your role to continue",
    "auth.admin": "Admin",
    "auth.supervisor": "Supervisor",
    "auth.driver": "Driver",
    "auth.logout": "Logout",
    "representative": "Representative",

    // Navigation
    "nav.overview": "Overview",
    "nav.drivers": "Drivers",
    "nav.customers": "Customers",
    "nav.deliveries": "Deliveries",
    "nav.vehicles": "Vehicle Fleet",
    "nav.tracking": "Live Tracking",
    "nav.analytics": "Analytics",
    "nav.alerts": "Alerts & Notifications",
    "nav.settings": "System Settings",
    "nav.adminPanel": "Admin Panel",
    "nav.userManagement": "User Management",
    "nav.driverManagement": "Driver Management",
    "nav.customerManagement": "Customer Management",
    "nav.deliveryTasks": "Delivery Tasks",

    // Dashboard
    "dashboard.welcome": "Welcome to Al-Rafidain Delivery Management",
    "dashboard.totalDeliveries": "Total Deliveries",
    "dashboard.activeDrivers": "Active Drivers",
    "dashboard.totalRevenue": "Total Revenue",
    "dashboard.avgDeliveryTime": "Avg Delivery Time",
    "dashboard.quickActions": "Quick Actions",
    "dashboard.welcomeBack": "Welcome back",
    "dashboard.deliveryOverview": "Here's your delivery overview for today",
    "dashboard.driverDashboard": "Driver Dashboard",

    // Supervisor Actions
    "supervisor.assignDelivery": "Assign Delivery",
    "supervisor.manageDrivers": "Manage Drivers",
    "supervisor.viewReports": "View Reports",
    "supervisor.trackVehicles": "Track Vehicles",

    // Driver Dashboard
    "driver.todayDeliveries": "Today's Deliveries",
    "driver.completedDeliveries": "Completed Deliveries",
    "driver.earnings": "Earnings",
    "driver.rating": "Rating",
    "driver.assignedDeliveries": "Assigned Deliveries",
    "driver.notifications": "Notifications",
    "driver.clockIn": "Clock In",
    "driver.clockOut": "Clock Out",
    "driver.shareLocation": "Share Location",
    "driver.reportIssue": "Report Issue",
    "driver.todayEarnings": "Today's Earnings",
    "driver.driverRating": "Driver Rating",
    "driver.hoursWorked": "Hours Worked",
    "driver.milesDriven": "Miles Driven",
    "driver.vehicleStatus": "Vehicle Status",
    "driver.total": "Total",
    "driver.deliveries": "deliveries",
    "driver.fromYesterday": "from yesterday",
    "driver.basedOnReviews": "Based on reviews",
    "driver.target": "Target",
    "driver.today": "today",
    "driver.avg": "Avg",
    "driver.milesPerDelivery": "miles/delivery",
    "driver.fuel": "Fuel",
    "driver.nextService": "Next service",
    "driver.days": "days",
    "driver.good": "Good",

    // Admin Overview
    totalRevenue: "Total Revenue",
    activeDrivers: "Active Drivers",
    fleetVehicles: "Fleet Vehicles",
    deliveriesToday: "Deliveries Today",
    onRoute: "on route",
    maintenance: "maintenance",
    completed: "completed",
    pending: "pending",
    performanceMetrics: "Performance Metrics",
    onTimeDeliveryRate: "On-time Delivery Rate",
    customerSatisfaction: "Customer Satisfaction",
    fleetUtilization: "Fleet Utilization",
    driverEfficiency: "Driver Efficiency",
    systemAlerts: "System Alerts",
    high: "High",
    medium: "Medium",
    delayed: "Delayed",
    recentActivity: "Recent Activity",
    minutesAgo: "minutes ago",
    hoursAgo: "hours ago",

    // Driver Management
    driverManagement: "Driver Management",
    manageDeliveryTeam: "Manage your delivery team and monitor performance",
    export: "Export",
    add: "Add",
    driver: "Driver",
    avgRating: "Avg Rating",
    offline: "Offline",
    searchDrivers: "Search drivers by name or email...",
    filter: "Filter",
    vehicle: "Vehicle",
    viewProfile: "View Profile",
    assignTask: "Assign Task",
    viewHistory: "View History",
    sendMessage: "Send Message",
    suspend: "Suspend",
    "driver.addNew": "Add New Driver",
    "driver.personalInfo": "Personal Information",
    "driver.workInfo": "Work Information",
    "driver.fullName": "Full Name",
    "driver.nameRequired": "Name is required",
    "driver.emailAddress": "Email Address",
    "driver.emailRequired": "Email is required",
    "driver.invalidEmail": "Invalid email format",
    "driver.phoneNumber": "Phone Number",
    "driver.phoneRequired": "Phone is required",
    "driver.homeAddress": "Address",
    "driver.enterAddress": "Enter home address",
    "driver.licenseNumber": "Driver's License Number",
    "driver.licenseRequired": "License number is required",
    "driver.assignedVehicle": "Assigned Vehicle",
    "driver.vehicleRequired": "Vehicle assignment is required",
    "driver.selectVehicle": "Select a vehicle",
    "driver.emergencyContact": "Emergency Contact",
    "driver.emergencyPlaceholder": "Name and phone number",
    "driver.initialStatus": "Initial Status",
    "driver.addDriver": "Add Driver",
    "driver.addingDriver": "Adding Driver...",
    "driver.registrationNote":
      "Please ensure all required information is accurate. The driver will receive login credentials via email after registration.",

    // Customer Management
    customerManagement: "Customer Management",
    manageCustomerRelationships: "Manage customer relationships and track delivery history",
    activeCustomers: "Active Customers",
    vipCustomers: "VIP Customers",
    inactive: "Inactive",
    searchCustomers: "Search customers by name, email, or ID...",
    createOrder: "Create Order",
    deactivate: "Deactivate",
    "customer.addNew": "Add New Customer",
    "customer.personalInfo": "Personal Information",
    "customer.deliveryInfo": "Delivery Information",
    "customer.fullName": "Full Name",
    "customer.nameRequired": "Name is required",
    "customer.emailAddress": "Email Address",
    "customer.emailRequired": "Email is required",
    "customer.invalidEmail": "Invalid email format",
    "customer.phoneNumber": "Phone Number",
    "customer.phoneRequired": "Phone is required",
    "customer.customerStatus": "Customer Status",
    "customer.deliveryAddress": "Delivery Address",
    "customer.addressRequired": "Address is required",
    "customer.enterAddress": "Enter complete delivery address",
    "customer.preferredTime": "Preferred Delivery Time",
    "customer.morning": "Morning (9-12 PM)",
    "customer.afternoon": "Afternoon (1-5 PM)",
    "customer.evening": "Evening (5-8 PM)",
    "customer.flexible": "Flexible",
    "customer.notes": "Notes",
    "customer.notesPlaceholder": "Special delivery instructions or customer notes",
    "customer.addCustomer": "Add Customer",
    "customer.addingCustomer": "Adding Customer...",
    "customer.infoNote":
      "Customer information will be used for delivery coordination and communication. Ensure all contact details are accurate.",

    // Vehicle Fleet
    vehicleFleetManagement: "Vehicle Fleet Management",
    manageMonitorFleet: "Manage and monitor your delivery fleet",
    addVehicle: "Add Vehicle",
    totalVehicles: "Total Vehicles",
    active: "Active",
    lowFuel: "Low Fuel",
    allVehicles: "All Vehicles",
    maintenanceSchedule: "Maintenance Schedule",
    fuelManagement: "Fuel Management",
    searchVehicles: "Search vehicles...",
    fuelLevel: "Fuel Level",
    mileage: "Mileage",
    location: "Location",

    // Live Tracking
    liveTracking: "Live Tracking",
    realTimeMonitoring: "Real-time monitoring of active deliveries",
    fullMapView: "Full Map View",
    activeDeliveries: "Active Deliveries",
    inTransit: "In Transit",
    completedToday: "Completed Today",
    liveMap: "Live Map",
    realTimeDriverLocations: "Real-time driver locations",
    interactiveMap: "Interactive map would be displayed here",
    currentlyInProgress: "Currently in progress",
    routeOptimization: "Route Optimization",
    deliveryHistory: "Delivery History",

    // Analytics
    analyticsDashboard: "Analytics Dashboard",
    performanceInsights: "Performance insights and business metrics",
    overview: "Overview",
    driverPerformance: "Driver Performance",
    routeAnalytics: "Route Analytics",
    customerInsights: "Customer Insights",
    deliveryTrends: "Delivery Trends",
    revenueAnalytics: "Revenue Analytics",
    onTimeDelivery: "On-Time Delivery Rate",
    averageCustomerRating: "Average Customer Rating",
    avgDistancePerDelivery: "Avg Distance per Delivery",
    driverPerformanceLeaderboard: "Driver Performance Leaderboard",
    topPerformingDrivers: "Top performing drivers this month",
    routeEfficiency: "Route Efficiency",
    excellent: "Excellent",

    // Alerts & Notifications
    alertsNotifications: "Alerts & Notifications",
    monitorSystemAlerts: "Monitor system alerts and configure notifications",
    activeAlerts: "Active",
    criticalAlerts: "Critical Alerts",
    warnings: "Warnings",
    infoAlerts: "Info Alerts",
    resolvedToday: "Resolved Today",
    resolved: "Resolved",
    notificationSettings: "Notification Settings",
    notificationPreferences: "Notification Preferences",
    configureAlerts: "Configure which alerts you want to receive",
    lowFuelAlerts: "Low Fuel Alerts",
    delayedDeliveries: "Delayed Deliveries",
    vehicleMaintenance: "Vehicle Maintenance",
    customerFeedback: "Customer Feedback",
    systemUpdates: "System Updates",
    savePreferences: "Save Preferences",

    // Visit Management
    visitManagement: "Visit Management",
    monitorDelegateVisits: "Monitor and manage delegate visits",
    scheduleVisit: "Schedule Visit",
    createNewVisit: "Create a new visit for a delegate",
    delegate: "Delegate",
    selectDelegate: "Select delegate",
    customerName: "Customer Name",
    enterCustomerName: "Enter customer name",
    customerAddress: "Customer Address",
    enterCustomerAddress: "Enter customer address",
    visitType: "Visit Type",
    delivery: "Delivery",
    pickup: "Pickup",
    inspection: "Inspection",
    maintenance: "Maintenance",
    meeting: "Meeting",
    priority: "Priority",
    low: "Low",
    medium: "Medium",
    high: "High",
    urgent: "Urgent",
    duration: "Duration (minutes)",
    startTime: "Start Time",
    endTime: "End Time",
    notes: "Notes",
    additionalNotes: "Additional notes for this visit",
    visitDetails: "Visit Details",
    scheduledStart: "Scheduled Start",
    scheduledEnd: "Scheduled End",
    allowedDuration: "Allowed Duration",
    viewDetails: "View Details",
    activeAlerts: "Active Alerts",
    visitAlerts: "Visit Alerts",
    noVisitAlerts: "No Visit Alerts",
    allVisitsOnSchedule: "All visits are on schedule and within time limits.",
    markAsRead: "Mark as Read",
    lateVisitAlert: "Late Visit Alert",
    timeExceededAlert: "Time Exceeded Alert",
    noShowAlert: "No Show Alert",
    earlyCompletionAlert: "Early Completion Alert",
    visitId: "Visit ID",
    delegateId: "Delegate ID",
    lateArrival: "Late Arrival",
    timeExceeded: "Time Exceeded",
    noShow: "No Show",
    earlyCompletion: "Early Completion",
    critical: "Critical",
    warning: "Warning",
    info: "Info",
    success: "Success",
    resolved: "Resolved",
    resolve: "Resolve",

    // Internal Messaging
    internalMessaging: "Internal Messaging",
    communicateWithStaff: "Communicate with staff and use the chatbot",
    composeMessage: "Compose Message",
    sendMessageToStaff: "Send a message to a staff member",
    recipient: "Recipient",
    selectRecipient: "Select recipient",
    subject: "Subject",
    enterMessageSubject: "Enter message subject",
    message: "Message",
    enterYourMessage: "Enter your message",
    sendMessage: "Send Message",
    messages: "Messages",
    searchMessages: "Search messages...",
    from: "From",
    to: "To",
    sent: "Sent",
    new: "NEW",
    unread: "Unread",
    noUnreadMessages: "No unread messages",
    chatBot: "Chat Bot",
    askQuestionsAboutVisits: "Ask questions about visits, delegates, or system information",
    typeYourMessage: "Type your message...",
    askMeAnything: "Ask me anything...",
    todaysVisits: "Today's Visits",
    activeAlerts: "Active Alerts",
    delegateStatus: "Delegate Status",
    deliveryInfo: "Delivery Info",
    internalChatBot: "Internal Chat Bot",
    online: "Online",
    aiAssistant: "AI Assistant",
    welcomeToAssistant: "Welcome to Al-Rafidain Industrial Company's assistant. I can help you with:",
    visitSchedules: "Visit schedules and delegate information",
    systemAlerts: "System alerts and notifications",
    deliveryTracking: "Delivery tracking and status updates",
    companyInformation: "General company information",
    howCanIAssist: "How can I assist you today?",
    quickActions: "Quick Actions",

    // Chatbot Responses
    chatbotResponses: {
      visitInfo: "I can help you with visit information! Here's what I found:",
      todaysVisits: "Today's Visits:",
      delegateStatus: "Here's the current delegate status:",
      activeDelegates: "Active Delegates:",
      allDelegatesActive: "All delegates are currently active and ready for assignments.",
      currentAlerts: "Current Alerts:",
      deliveryStatus: "Delivery Status:",
      inTransit: "In Transit",
      completedToday: "Completed Today",
      scheduled: "Scheduled",
      averageDeliveryTime: "Average delivery time",
      onTimeDeliveryRate: "On-time delivery rate",
      fleetStatus: "Fleet Status:",
      activeVehicles: "Active Vehicles",
      inMaintenance: "In Maintenance",
      fuelLevel: "Fuel Level",
      maintenanceAlerts: "Maintenance Alerts:",
      timeManagement: "Time Management:",
      currentTime: "Current Time",
      lateVisits: "Late Visits",
      exceededTime: "Exceeded Time",
      locationInformation: "Location Information:",
      activeZones: "Active Zones",
      coverageAreas: "Coverage Areas",
      currentOperations: "Current Operations",
      greeting: "Hello! Welcome to Al-Rafidain Industrial Company's assistant. I'm here to help you with:",
      helpTopics: "I'm here to help! Here are some things you can ask me:",
      visitManagement: "Visit Management:",
      delegateInformation: "Delegate Information:",
      systemAlerts: "System Alerts:",
      deliveryTracking: "Delivery Tracking:",
      justAsk: "Just ask me anything!",
      defaultResponse: "I understand you're asking about:",
      beMoreSpecific: "I can help you with visit management, delegate tracking, system alerts, delivery information, and vehicle fleet status. Could you be more specific about what you need?",
      tryAsking: "Try asking:",
      showTodaysVisits: "Show me today's visits",
      anyAlerts: "Any alerts?",
      delegateStatus: "Delegate status",
      deliveryInformation: "Delivery information"
    },

    // After-Sales Support
    afterSalesSupport: "After-Sales Support",
    manageCustomerSupport: "Manage customer inquiries, complaints, maintenance, and warranties",
    newSupportCase: "New Support Case",
    customerInquiries: "Customer Inquiries",
    complaints: "Complaints",
    maintenanceRequests: "Maintenance Requests",
    warrantyManagement: "Warranty Management",
    followUpServices: "Follow-up Services",
    totalInquiries: "Total Inquiries",
    resolvedInquiries: "Resolved Inquiries",
    activeComplaints: "Active Complaints",
    escalationRate: "Escalation Rate",
    customerSatisfaction: "Customer Satisfaction",
    averageRating: "Average Rating",
    warrantyOverview: "Warranty Overview",
    activeWarranties: "Active Warranties",
    warrantyClaims: "Warranty Claims",
    approvalRate: "Approval Rate",
    performanceMetrics: "Performance Metrics",
    avgResolutionTime: "Avg Resolution Time",
    avgMaintenanceCost: "Avg Maintenance Cost",
    customerRetention: "Customer Retention",
    scheduled: "Scheduled",
    completed: "Completed",
    completionRate: "Completion Rate",
    searchInquiries: "Search inquiries...",
    searchComplaints: "Search complaints...",
    searchMaintenance: "Search maintenance...",
    searchWarranties: "Search warranties...",
    searchFollowUps: "Search follow-ups...",
    general: "General",
    technical: "Technical",
    billing: "Billing",
    warranty: "Warranty",
    complaint: "Complaint",
    maintenance: "Maintenance",
    productQuality: "Product Quality",
    deliveryIssue: "Delivery Issue",
    serviceQuality: "Service Quality",
    billingError: "Billing Error",
    communication: "Communication",
    other: "Other",
    investigating: "Investigating",
    escalated: "Escalated",
    preventive: "Preventive",
    corrective: "Corrective",
    emergency: "Emergency",
    upgrade: "Upgrade",
    requested: "Requested",
    cancelled: "Cancelled",
    standard: "Standard",
    extended: "Extended",
    premium: "Premium",
    expired: "Expired",
    void: "Void",
    transferred: "Transferred",
    submitted: "Submitted",
    underReview: "Under Review",
    approved: "Approved",
    rejected: "Rejected",
    rescheduled: "Rescheduled",
    satisfactionSurvey: "Satisfaction Survey",
    productTraining: "Product Training",
    maintenanceReminder: "Maintenance Reminder",
    upgradeOffer: "Upgrade Offer",
    feedbackCollection: "Feedback Collection",
    equipmentMaintenance: "Equipment Maintenance",
    warrantyCovered: "WARRANTY",
    claims: "CLAIMS",
    expires: "Expires",
    months: "months",
    level: "Level",
    technician: "Technician",
    nextFollowUp: "Next follow-up",
    assignedTo: "Assigned to",

    // Settings
    systemSettings: "System Settings",
    configureSystem: "Configure system preferences and company settings",
    companyInformation: "Company Information",
    companyName: "Company Name",
    address: "Address",
    phone: "Phone",
    email: "Email",
    website: "Website",
    operationalSettings: "Operational Settings",
    workingHours: "Working Hours",
    customerTypes: "Customer Types",
    coverageZones: "Coverage Zones",
    startTime: "Start Time",
    endTime: "End Time",
    deliveryRadius: "Delivery Radius",
    maxDeliveriesPerDriver: "Max Deliveries per Driver",
    userManagement: "User Management",
    systemPreferences: "System Preferences",
    backupRestore: "Backup & Restore",

    // Common
    "common.search": "Search",
    "common.filter": "Filter",
    "common.add": "Add",
    "common.edit": "Edit",
    "common.delete": "Delete",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.close": "Close",
    "common.status": "Status",
    "common.actions": "Actions",
    "common.loading": "Loading...",
    "common.successRate": "Success Rate",
    "common.fromLastWeek": "from last week",
    "common.onRoute": "on route",

    // Task Management
    "task.createNew": "Create New Delivery Task",
    "task.taskDetails": "Task Details",
    "task.title": "Task Title",
    "task.titleRequired": "Task title is required",
    "task.priority": "Priority Level",
    "task.low": "Low",
    "task.medium": "Medium",
    "task.high": "High",
    "task.urgent": "Urgent",
    "task.items": "Items to Deliver",
    "task.itemsRequired": "Items description is required",
    "task.itemsPlaceholder": "Laptop, Mouse, Keyboard (separate with commas)",
    "task.specialInstructions": "Special Instructions",
    "task.instructionsPlaceholder": "Handle with care, fragile items...",
    "task.assignment": "Assignment & Scheduling",
    "task.customer": "Customer",
    "task.customerRequired": "Customer selection is required",
    "task.selectCustomer": "Select customer",
    "task.assignDriver": "Assign Driver (Optional)",
    "task.unassigned": "Unassigned",
    "task.available": "Available",
    "task.noDriversAvailable": "No drivers currently available",
    "task.scheduledDateTime": "Scheduled Date & Time",
    "task.scheduledRequired": "Scheduled time is required",
    "task.estimatedDuration": "Estimated Duration",
    "task.estimatedRequired": "Estimated time is required",
    "task.selectEstimatedTime": "Select estimated time",
    "task.15mins": "15 minutes",
    "task.30mins": "30 minutes",
    "task.45mins": "45 minutes",
    "task.60mins": "1 hour",
    "task.90mins": "1.5 hours",
    "task.120mins": "2 hours",
    "task.createTask": "Create Task",
    "task.creatingTask": "Creating Task...",
    "task.taskWillBeAssigned": "Task will be automatically assigned to the selected driver.",
    "task.taskWillBePending": "Task will be created as pending and can be assigned to a driver later.",

    // Task Details
    "taskDetails.taskInfo": "Task Information",
    "taskDetails.customerInfo": "Customer Information",
    "taskDetails.liveTracking": "Live Tracking",
    "taskDetails.taskHistory": "Task History",
    "taskDetails.details": "Details",
    "taskDetails.tracking": "Tracking",
    "taskDetails.history": "History",
    "taskDetails.editTask": "Edit Task",
    "taskDetails.taskId": "Task ID",
    "taskDetails.itemsToDeliver": "Items to Deliver",
    "taskDetails.scheduledTime": "Scheduled Time",
    "taskDetails.estimatedTime": "Estimated Time",
    "taskDetails.distance": "Distance",
    "taskDetails.noInstructions": "No special instructions",
    "taskDetails.assignedDriver": "Assigned Driver",
    "taskDetails.taskStatus": "Task Status",
    "taskDetails.viewRoute": "View Route",
    "taskDetails.customerName": "Customer Name",
    "taskDetails.contactInfo": "Contact Information",
    "taskDetails.callCustomer": "Call Customer",
    "taskDetails.sendMessage": "Send Message",
    "taskDetails.realTimeTracking": "Real-time Tracking",
    "taskDetails.trackDescription": "Track driver location and delivery progress in real-time",
    "taskDetails.openMapView": "Open Map View",
    "taskDetails.taskCreated": "Task created",
    "taskDetails.driverAssigned": "Driver assigned",
    "taskDetails.taskStarted": "Task started",

    // Supervisor
    "supervisor.assignNewDelivery": "Assign New Delivery",
    "supervisor.pickupAddress": "Pickup Address",
    "supervisor.deliveryAddress": "Delivery Address",
    "supervisor.scheduledTime": "Scheduled Time",
    "supervisor.lowPriority": "Low Priority",
    "supervisor.mediumPriority": "Medium Priority",
    "supervisor.highPriority": "High Priority",
    "supervisor.selectDriver": "Select available driver",
    "supervisor.enterPickup": "Enter pickup location",
    "supervisor.enterDelivery": "Enter delivery destination",
    "supervisor.specialInstructions": "Special Instructions",
    "supervisor.deliveryInstructions": "Any special delivery instructions...",
    "supervisor.assignDelivery": "Assign Delivery",

    // Driver Management
    "driverManagement": "Driver Management",
    "manageDeliveryTeam": "Manage your delivery team",
    "add": "Add",
    "driver": "Driver",
    "export": "Export",
    "searchDrivers": "Search drivers...",
    "filter": "Filter",
    "viewProfile": "View Profile",
    "assignTask": "Assign Task",
    "viewHistory": "View History",
    "sendMessage": "Send Message",
    "suspend": "Suspend",
    "activeDrivers": "Active Drivers",
    "onRoute": "On Route",
    "avgRating": "Average Rating",
    "offline": "Offline",
    "deliveries": "deliveries",
    "vehicle": "Vehicle",
    "liveTracking": "Live Tracking",
    "track": "Track",

    // ID Verification
    "idVerification": "ID Verification",
    "officialIdImage": "Official ID Image",
    "clickToUpload": "Click to upload",
    "uploadId": "official ID",
    "fileFormats": "PNG, JPG or PDF (MAX. 10MB)",
    "verified": "Verified",
    "verificationPending": "ID verification pending",
    "noIdUploaded": "No ID image uploaded",

    // Geographic Coverage
    "geographicCoverage": "Geographic Coverage Areas",
    "selectCoverageAreas": "Select Coverage Areas",
    "selectedAreas": "Selected areas:",
    "noCoverageAssigned": "No coverage areas assigned",
    "contactAdmin": "Contact admin to assign coverage areas",
    "downtownDistrict": "Downtown District",
    "northZone": "North Zone",
    "southZone": "South Zone",
    "eastDistrict": "East District",
    "westZone": "West Zone",
    "industrialArea": "Industrial Area",
    "residentialSectorA": "Residential Sector A",
    "residentialSectorB": "Residential Sector B",
    "businessDistrict": "Business District",
    "airportZone": "Airport Zone",

    // Live Tracking
    "liveLocationMap": "Live Location Map",
    "interactiveMapView": "Interactive Map View",
    "trackingActive": "Tracking active - Real-time location updates",
    "startTracking": "Click 'Start Tracking' to begin",
    "currentLocation": "Current Location:",
    "updated": "Updated:",
    "liveStatus": "Live Status",
    "tracking": "Tracking",
    "active": "ACTIVE",
    "inactive": "INACTIVE",
    "speed": "Speed:",
    "lastUpdate": "Last Update:",
    "call": "Call",
    "message": "Message",
    "vehicleInfo": "Vehicle Info",
    "startLiveTracking": "Start Live Tracking",
    "stopTracking": "Stop Tracking",
    "refresh": "Refresh",

    // Movement History
    "movementHistory": "Movement History",
    "recentDeliveries": "Recent Deliveries",
    "noMovementHistory": "No movement history available",
    "startTrackingToSee": "Start tracking to see location history",

    // Performance
    "performance": "Performance",
    "performanceMetrics": "Performance Metrics",
    "onTimeDelivery": "On-time Delivery",
    "customerRating": "Customer Rating",
    "routeEfficiency": "Route Efficiency",
    "safetyScore": "Safety Score",
    "monthlyStats": "Monthly Stats",
    "milesDriven": "Miles Driven",
    "successRate": "Success Rate",

    // Coverage Tab
    "coverage": "Coverage",
    "coverageAreas": "Geographic Coverage Areas",

    // Add Driver Modal
    "addNewDriver": "Add New Driver",
    "personalInformation": "Personal Information",
    "fullName": "Full Name",
    "enterFullName": "Enter full name",
    "emailAddress": "Email Address",
    "phoneNumber": "Phone Number",
    "address": "Address",
    "enterHomeAddress": "Enter home address",
    "workInformation": "Work Information",
    "driversLicenseNumber": "Driver's License Number",
    "assignedVehicle": "Assigned Vehicle",
    "selectVehicle": "Select a vehicle",
    "emergencyContact": "Emergency Contact",
    "nameAndPhone": "Name and phone number",
    "initialStatus": "Initial Status",
    "addingDriver": "Adding Driver...",
    "addDriver": "Add Driver",
    "cancel": "Cancel",
    "required": "required",
    "nameRequired": "Name is required",
    "emailRequired": "Email is required",
    "invalidEmail": "Invalid email format",
    "phoneRequired": "Phone is required",
    "licenseRequired": "License number is required",
    "vehicleRequired": "Vehicle assignment is required",
    "idImageRequired": "Official ID image is required",
    "coverageRequired": "At least one coverage area is required",
    "ensureAccuracy": "Please ensure all required information is accurate. The driver will receive login credentials via email after registration.",

    // Visits
    uploadTasks: "Upload Tasks",
    filterByDelegate: "Filter by Delegate",
    filterByRegion: "Filter by Region",
    filterByCustomer: "Filter by Customer",
    filterByDate: "Filter by Date",
    status: "Status",
    pending: "Pending",
    completed: "Completed",
    missed: "Missed",

    assistantTitle: "Al-Rafidain Assistant",
    hello: "Hello",
    send: "Send",
    minimize: "Minimize",
    maximize: "Open Assistant",
    provideFeedback: "Provide feedback",
    feedbackThanks: "Thanks for your feedback!",
    helpful: "Helpful",
    notHelpful: "Not helpful",
    optionalComment: "Optional comment",
    submit: "Submit",
  },
  ar: {
    // Auth
    "auth.login": "تسجيل الدخول",
    "auth.email": "البريد الإلكتروني",
    "auth.password": "كلمة المرور",
    "auth.signIn": "تسجيل الدخول",
    "auth.selectRole": "اختر دورك للمتابعة",
    "auth.admin": "مسؤول",
    "auth.supervisor": "مشرف",
    "auth.representative": "ممثل",
    "auth.logout": "تسجيل الخروج",

    // Navigation
    "nav.overview": "نظرة عامة",
    "nav.drivers": "السائقين",
    "nav.customers": "العملاء",
    "nav.deliveries": "التوصيلات",
    "nav.vehicles": "أسطول المركبات",
    "nav.tracking": "التتبع المباشر",
    "nav.analytics": "التحليلات",
    "nav.alerts": "التنبيهات والإشعارات",
    "nav.settings": "إعدادات النظام",
    "nav.adminPanel": "لوحة الإدارة",
    "nav.userManagement": "إدارة المستخدمين",
    "nav.driverManagement": "إدارة السائقين",
    "nav.customerManagement": "إدارة العملاء",
    "nav.deliveryTasks": "مهام التوصيل",

    // Dashboard
    "dashboard.welcome": "مرحباً بك في نظام إدارة التوصيل - الرفيدان",
    "dashboard.totalDeliveries": "إجمالي التوصيلات",
    "dashboard.activeDrivers": "السائقين النشطين",
    "dashboard.totalRevenue": "إجمالي الإيرادات",
    "dashboard.avgDeliveryTime": "متوسط وقت التوصيل",
    "dashboard.quickActions": "الإجراءات السريعة",
    "dashboard.welcomeBack": "مرحباً بعودتك",
    "dashboard.deliveryOverview": "إليك نظرة عامة على توصيلاتك لليوم",
    "dashboard.driverDashboard": "لوحة تحكم السائق",

    // Supervisor Actions
    "supervisor.assignDelivery": "تعيين توصيل",
    "supervisor.manageDrivers": "إدارة السائقين",
    "supervisor.viewReports": "عرض التقارير",
    "supervisor.trackVehicles": "تتبع المركبات",

    // Driver Dashboard
    "driver.todayDeliveries": "توصيلات اليوم",
    "driver.completedDeliveries": "التوصيلات المكتملة",
    "driver.earnings": "الأرباح",
    "driver.rating": "التقييم",
    "driver.assignedDeliveries": "التوصيلات المعينة",
    "driver.notifications": "الإشعارات",
    "driver.clockIn": "تسجيل الحضور",
    "driver.clockOut": "تسجيل الانصراف",
    "driver.shareLocation": "مشاركة الموقع",
    "driver.reportIssue": "الإبلاغ عن مشكلة",
    "driver.todayEarnings": "أرباح اليوم",
    "driver.driverRating": "تقييم السائق",
    "driver.hoursWorked": "ساعات العمل",
    "driver.milesDriven": "الأميال المقطوعة",
    "driver.vehicleStatus": "حالة المركبة",
    "driver.total": "المجموع",
    "driver.deliveries": "توصيلة",
    "driver.fromYesterday": "من الأمس",
    "driver.basedOnReviews": "بناءً على التقييمات",
    "driver.target": "الهدف",
    "driver.today": "اليوم",
    "driver.avg": "المتوسط",
    "driver.milesPerDelivery": "ميل/توصيلة",
    "driver.fuel": "الوقود",
    "driver.nextService": "الصيانة القادمة",
    "driver.days": "أيام",
    "driver.good": "جيد",

    // Admin Overview
    totalRevenue: "إجمالي الإيرادات",
    activeDrivers: "السائقين النشطين",
    fleetVehicles: "مركبات الأسطول",
    deliveriesToday: "توصيلات اليوم",
    onRoute: "في الطريق",
    maintenance: "صيانة",
    completed: "مكتمل",
    pending: "معلق",
    performanceMetrics: "مقاييس الأداء",
    onTimeDeliveryRate: "معدل التوصيل في الوقت المحدد",
    customerSatisfaction: "رضا العملاء",
    fleetUtilization: "استخدام الأسطول",
    driverEfficiency: "كفاءة السائق",
    systemAlerts: "تنبيهات النظام",
    high: "عالي",
    medium: "متوسط",
    delayed: "متأخر",
    recentActivity: "النشاط الأخير",
    minutesAgo: "دقائق مضت",
    hoursAgo: "ساعات مضت",

    // Driver Management
    driverManagement: "إدارة السائقين",
    manageDeliveryTeam: "إدارة فريق التوصيل ومراقبة الأداء",
    export: "تصدير",
    add: "إضافة",
    driver: "سائق",
    avgRating: "متوسط التقييم",
    offline: "غير متصل",
    searchDrivers: "البحث عن السائقين بالاسم أو البريد الإلكتروني...",
    filter: "تصفية",
    vehicle: "المركبة",
    viewProfile: "عرض الملف الشخصي",
    assignTask: "تعيين مهمة",
    viewHistory: "عرض التاريخ",
    sendMessage: "إرسال رسالة",
    suspend: "إيقاف",
    "driver.addNew": "إضافة سائق جديد",
    "driver.personalInfo": "المعلومات الشخصية",
    "driver.workInfo": "معلومات العمل",
    "driver.fullName": "الاسم الكامل",
    "driver.nameRequired": "الاسم مطلوب",
    "driver.emailAddress": "عنوان البريد الإلكتروني",
    "driver.emailRequired": "البريد الإلكتروني مطلوب",
    "driver.invalidEmail": "تنسيق البريد الإلكتروني غير صحيح",
    "driver.phoneNumber": "رقم الهاتف",
    "driver.phoneRequired": "رقم الهاتف مطلوب",
    "driver.homeAddress": "العنوان",
    "driver.enterAddress": "أدخل عنوان المنزل",
    "driver.licenseNumber": "رقم رخصة القيادة",
    "driver.licenseRequired": "رقم الرخصة مطلوب",
    "driver.assignedVehicle": "المركبة المعينة",
    "driver.vehicleRequired": "تعيين المركبة مطلوب",
    "driver.selectVehicle": "اختر مركبة",
    "driver.emergencyContact": "جهة الاتصال الطارئة",
    "driver.emergencyPlaceholder": "الاسم ورقم الهاتف",
    "driver.initialStatus": "الحالة الأولية",
    "driver.addDriver": "إضافة سائق",
    "driver.addingDriver": "جاري إضافة السائق...",
    "driver.registrationNote":
      "يرجى التأكد من دقة جميع المعلومات المطلوبة. سيتلقى السائق بيانات تسجيل الدخول عبر البريد الإلكتروني بعد التسجيل.",

    // Customer Management
    customerManagement: "إدارة العملاء",
    manageCustomerRelationships: "إدارة علاقات العملاء وتتبع تاريخ التوصيل",
    activeCustomers: "العملاء النشطين",
    vipCustomers: "عملاء VIP",
    inactive: "غير نشط",
    searchCustomers: "البحث عن العملاء بالاسم أو البريد الإلكتروني أو المعرف...",
    createOrder: "إنشاء طلب",
    deactivate: "إلغاء التفعيل",
    "customer.addNew": "إضافة عميل جديد",
    "customer.personalInfo": "المعلومات الشخصية",
    "customer.deliveryInfo": "معلومات التوصيل",
    "customer.fullName": "الاسم الكامل",
    "customer.nameRequired": "الاسم مطلوب",
    "customer.emailAddress": "عنوان البريد الإلكتروني",
    "customer.emailRequired": "البريد الإلكتروني مطلوب",
    "customer.invalidEmail": "تنسيق البريد الإلكتروني غير صحيح",
    "customer.phoneNumber": "رقم الهاتف",
    "customer.phoneRequired": "رقم الهاتف مطلوب",
    "customer.customerStatus": "حالة العميل",
    "customer.deliveryAddress": "عنوان التوصيل",
    "customer.addressRequired": "العنوان مطلوب",
    "customer.enterAddress": "أدخل عنوان التوصيل الكامل",
    "customer.preferredTime": "الوقت المفضل للتوصيل",
    "customer.morning": "الصباح (9-12 ظهراً)",
    "customer.afternoon": "بعد الظهر (1-5 مساءً)",
    "customer.evening": "المساء (5-8 مساءً)",
    "customer.flexible": "مرن",
    "customer.notes": "ملاحظات",
    "customer.notesPlaceholder": "تعليمات توصيل خاصة أو ملاحظات العميل",
    "customer.addCustomer": "إضافة عميل",
    "customer.addingCustomer": "جاري إضافة العميل...",
    "customer.infoNote": "ستُستخدم معلومات العميل لتنسيق التوصيل والتواصل. تأكد من دقة جميع تفاصيل الاتصال.",

    // Vehicle Fleet
    vehicleFleetManagement: "إدارة أسطول المركبات",
    manageMonitorFleet: "إدارة ومراقبة أسطول التوصيل الخاص بك",
    addVehicle: "إضافة مركبة",
    totalVehicles: "إجمالي المركبات",
    active: "نشط",
    lowFuel: "وقود منخفض",
    allVehicles: "جميع المركبات",
    maintenanceSchedule: "جدول الصيانة",
    fuelManagement: "إدارة الوقود",
    searchVehicles: "البحث عن المركبات...",
    fuelLevel: "مستوى الوقود",
    mileage: "المسافة المقطوعة",
    location: "الموقع",

    // Live Tracking
    liveTracking: "التتبع المباشر",
    realTimeMonitoring: "مراقبة التوصيلات النشطة في الوقت الفعلي",
    fullMapView: "عرض الخريطة الكاملة",
    activeDeliveries: "التوصيلات النشطة",
    inTransit: "في الطريق",
    completedToday: "مكتمل اليوم",
    liveMap: "الخريطة المباشرة",
    realTimeDriverLocations: "مواقع السائقين في الوقت الفعلي",
    interactiveMap: "ستظهر الخريطة التفاعلية هنا",
    currentlyInProgress: "قيد التنفيذ حالياً",
    routeOptimization: "تحسين المسار",
    deliveryHistory: "تاريخ التوصيل",

    // Analytics
    analyticsDashboard: "لوحة التحليلات",
    performanceInsights: "رؤى الأداء ومقاييس الأعمال",
    overview: "نظرة عامة",
    driverPerformance: "أداء السائق",
    routeAnalytics: "تحليلات المسار",
    customerInsights: "رؤى العملاء",
    deliveryTrends: "اتجاهات التوصيل",
    revenueAnalytics: "تحليلات الإيرادات",
    onTimeDelivery: "معدل التوصيل في الوقت المحدد",
    averageCustomerRating: "متوسط تقييم العملاء",
    avgDistancePerDelivery: "متوسط المسافة لكل توصيلة",
    driverPerformanceLeaderboard: "لوحة صدارة أداء السائقين",
    topPerformingDrivers: "أفضل السائقين أداءً هذا الشهر",
    routeEfficiency: "كفاءة المسار",
    excellent: "ممتاز",

    // Alerts & Notifications
    alertsNotifications: "التنبيهات والإشعارات",
    monitorSystemAlerts: "مراقبة تنبيهات النظام وتكوين الإشعارات",
    activeAlerts: "نشط",
    criticalAlerts: "التنبيهات الحرجة",
    warnings: "التحذيرات",
    infoAlerts: "تنبيهات المعلومات",
    resolvedToday: "تم حلها اليوم",
    resolved: "تم الحل",
    notificationSettings: "إعدادات الإشعارات",
    notificationPreferences: "تفضيلات الإشعارات",
    configureAlerts: "تكوين التنبيهات التي تريد تلقيها",
    lowFuelAlerts: "تنبيهات الوقود المنخفض",
    delayedDeliveries: "التوصيلات المتأخرة",
    vehicleMaintenance: "صيانة المركبات",
    customerFeedback: "ملاحظات العملاء",
    systemUpdates: "تحديثات النظام",
    savePreferences: "حفظ التفضيلات",

    // Settings
    systemSettings: "إعدادات النظام",
    configureSystem: "تكوين تفضيلات النظام وإعدادات الشركة",
    companyInformation: "معلومات الشركة",
    companyName: "اسم الشركة",
    address: "العنوان",
    phone: "الهاتف",
    email: "البريد الإلكتروني",
    website: "الموقع الإلكتروني",
    operationalSettings: "الإعدادات التشغيلية",
    workingHours: "ساعات العمل",
    customerTypes: "أنواع العملاء",
    coverageZones: "مناطق التغطية",
    startTime: "وقت البدء",
    endTime: "وقت الانتهاء",
    deliveryRadius: "نطاق التوصيل",
    maxDeliveriesPerDriver: "الحد الأقصى للتوصيلات لكل سائق",
    userManagement: "إدارة المستخدمين",
    systemPreferences: "تفضيلات النظام",
    backupRestore: "النسخ الاحتياطي والاستعادة",

    // Common
    "common.search": "بحث",
    "common.filter": "تصفية",
    "common.add": "إضافة",
    "common.edit": "تعديل",
    "common.delete": "حذف",
    "common.save": "حفظ",
    "common.cancel": "إلغاء",
    "common.close": "إغلاق",
    "common.status": "الحالة",
    "common.actions": "الإجراءات",
    "common.loading": "جاري التحميل...",
    "common.successRate": "معدل النجاح",
    "common.fromLastWeek": "من الأسبوع الماضي",
    "common.onRoute": "في الطريق",

    // Task Management
    "task.createNew": "إنشاء مهمة توصيل جديدة",
    "task.taskDetails": "تفاصيل المهمة",
    "task.title": "عنوان المهمة",
    "task.titleRequired": "عنوان المهمة مطلوب",
    "task.priority": "مستوى الأولوية",
    "task.low": "منخفض",
    "task.medium": "متوسط",
    "task.high": "عالي",
    "task.urgent": "عاجل",
    "task.items": "العناصر المراد توصيلها",
    "task.itemsRequired": "وصف العناصر مطلوب",
    "task.itemsPlaceholder": "لابتوب، ماوس، لوحة مفاتيح (افصل بفواصل)",
    "task.specialInstructions": "تعليمات خاصة",
    "task.instructionsPlaceholder": "التعامل بحذر، عناصر قابلة للكسر...",
    "task.assignment": "التعيين والجدولة",
    "task.customer": "العميل",
    "task.customerRequired": "اختيار العميل مطلوب",
    "task.selectCustomer": "اختر العميل",
    "task.assignDriver": "تعيين سائق (اختياري)",
    "task.unassigned": "غير معين",
    "task.available": "متاح",
    "task.noDriversAvailable": "لا يوجد سائقين متاحين حالياً",
    "task.scheduledDateTime": "التاريخ والوقت المجدول",
    "task.scheduledRequired": "الوقت المجدول مطلوب",
    "task.estimatedDuration": "المدة المقدرة",
    "task.estimatedRequired": "الوقت المقدر مطلوب",
    "task.selectEstimatedTime": "اختر الوقت المقدر",
    "task.15mins": "15 دقيقة",
    "task.30mins": "30 دقيقة",
    "task.45mins": "45 دقيقة",
    "task.60mins": "ساعة واحدة",
    "task.90mins": "ساعة ونصف",
    "task.120mins": "ساعتان",
    "task.createTask": "إنشاء مهمة",
    "task.creatingTask": "جاري إنشاء المهمة...",
    "task.taskWillBeAssigned": "سيتم تعيين المهمة تلقائياً للسائق المحدد.",
    "task.taskWillBePending": "سيتم إنشاء المهمة كمعلقة ويمكن تعيينها لسائق لاحقاً.",

    // Task Details
    "taskDetails.taskInfo": "معلومات المهمة",
    "taskDetails.customerInfo": "معلومات العميل",
    "taskDetails.liveTracking": "التتبع المباشر",
    "taskDetails.taskHistory": "تاريخ المهمة",
    "taskDetails.details": "التفاصيل",
    "taskDetails.tracking": "التتبع",
    "taskDetails.history": "التاريخ",
    "taskDetails.editTask": "تعديل المهمة",
    "taskDetails.taskId": "معرف المهمة",
    "taskDetails.itemsToDeliver": "العناصر المراد توصيلها",
    "taskDetails.scheduledTime": "الوقت المجدول",
    "taskDetails.estimatedTime": "الوقت المقدر",
    "taskDetails.distance": "المسافة",
    "taskDetails.noInstructions": "لا توجد تعليمات خاصة",
    "taskDetails.assignedDriver": "السائق المعين",
    "taskDetails.taskStatus": "حالة المهمة",
    "taskDetails.viewRoute": "عرض المسار",
    "taskDetails.customerName": "اسم العميل",
    "taskDetails.contactInfo": "معلومات الاتصال",
    "taskDetails.callCustomer": "اتصال بالعميل",
    "taskDetails.sendMessage": "إرسال رسالة",
    "taskDetails.realTimeTracking": "التتبع في الوقت الفعلي",
    "taskDetails.trackDescription": "تتبع موقع السائق وتقدم التوصيل في الوقت الفعلي",
    "taskDetails.openMapView": "فتح عرض الخريطة",
    "taskDetails.taskCreated": "تم إنشاء المهمة",
    "taskDetails.driverAssigned": "تم تعيين السائق",
    "taskDetails.taskStarted": "تم بدء المهمة",

    // Supervisor
    "supervisor.assignNewDelivery": "تعيين توصيل جديد",
    "supervisor.pickupAddress": "عنوان الاستلام",
    "supervisor.deliveryAddress": "عنوان التوصيل",
    "supervisor.scheduledTime": "الوقت المجدول",
    "supervisor.lowPriority": "أولوية منخفضة",
    "supervisor.mediumPriority": "أولوية متوسطة",
    "supervisor.highPriority": "أولوية عالية",
    "supervisor.selectDriver": "اختر سائق متاح",
    "supervisor.enterPickup": "أدخل موقع الاستلام",
    "supervisor.enterDelivery": "أدخل وجهة التوصيل",
    "supervisor.specialInstructions": "تعليمات خاصة",
    "supervisor.deliveryInstructions": "أي تعليمات توصيل خاصة...",
    "supervisor.assignDelivery": "تعيين التوصيل",

    // Driver Management
    "driverManagement": "إدارة السائقين",
    "manageDeliveryTeam": "إدارة فريق التوصيل الخاص بك",
    "add": "إضافة",
    "driver": "سائق",
    "export": "تصدير",
    "searchDrivers": "البحث عن السائقين...",
    "filter": "تصفية",
    "viewProfile": "عرض الملف الشخصي",
    "assignTask": "تعيين مهمة",
    "viewHistory": "عرض السجل",
    "sendMessage": "إرسال رسالة",
    "suspend": "تعليق",
    "activeDrivers": "السائقون النشطون",
    "onRoute": "في الطريق",
    "avgRating": "متوسط التقييم",
    "offline": "غير متصل",
    "deliveries": "توصيلات",
    "vehicle": "المركبة",
    "liveTracking": "التتبع المباشر",
    "track": "تتبع",

    // ID Verification
    "idVerification": "التحقق من الهوية",
    "officialIdImage": "صورة الهوية الرسمية",
    "clickToUpload": "انقر للرفع",
    "uploadId": "الهوية الرسمية",
    "fileFormats": "PNG، JPG أو PDF (حد أقصى 10 ميجابايت)",
    "verified": "تم التحقق",
    "verificationPending": "التحقق من الهوية معلق",
    "noIdUploaded": "لم يتم رفع صورة الهوية",

    // Geographic Coverage
    "geographicCoverage": "مناطق التغطية الجغرافية",
    "selectCoverageAreas": "اختر مناطق التغطية",
    "selectedAreas": "المناطق المختارة:",
    "noCoverageAssigned": "لم يتم تعيين مناطق تغطية",
    "contactAdmin": "اتصل بالإدارة لتعيين مناطق التغطية",
    "downtownDistrict": "منطقة وسط المدينة",
    "northZone": "المنطقة الشمالية",
    "southZone": "المنطقة الجنوبية",
    "eastDistrict": "المنطقة الشرقية",
    "westZone": "المنطقة الغربية",
    "industrialArea": "المنطقة الصناعية",
    "residentialSectorA": "القطاع السكني أ",
    "residentialSectorB": "القطاع السكني ب",
    "businessDistrict": "منطقة الأعمال",
    "airportZone": "منطقة المطار",

    // Live Tracking
    "liveLocationMap": "خريطة الموقع المباشر",
    "interactiveMapView": "عرض الخريطة التفاعلية",
    "trackingActive": "التتبع نشط - تحديثات الموقع في الوقت الفعلي",
    "startTracking": "انقر على 'بدء التتبع' للبدء",
    "currentLocation": "الموقع الحالي:",
    "updated": "تم التحديث:",
    "liveStatus": "الحالة المباشرة",
    "tracking": "التتبع",
    "active": "نشط",
    "inactive": "غير نشط",
    "speed": "السرعة:",
    "lastUpdate": "آخر تحديث:",
    "call": "اتصال",
    "message": "رسالة",
    "vehicleInfo": "معلومات المركبة",
    "startLiveTracking": "بدء التتبع المباشر",
    "stopTracking": "إيقاف التتبع",
    "refresh": "تحديث",

    // Movement History
    "movementHistory": "سجل الحركة",
    "recentDeliveries": "التوصيلات الأخيرة",
    "noMovementHistory": "لا يوجد سجل حركة متاح",
    "startTrackingToSee": "ابدأ التتبع لرؤية سجل المواقع",

    // Performance
    "performance": "الأداء",
    "performanceMetrics": "مقاييس الأداء",
    "onTimeDelivery": "التوصيل في الوقت المحدد",
    "customerRating": "تقييم العملاء",
    "routeEfficiency": "كفاءة المسار",
    "safetyScore": "درجة الأمان",
    "monthlyStats": "الإحصائيات الشهرية",
    "milesDriven": "الأميال المقطوعة",
    "successRate": "معدل النجاح",

    // Coverage Tab
    "coverage": "التغطية",
    "coverageAreas": "مناطق التغطية الجغرافية",

    // Add Driver Modal
    "addNewDriver": "إضافة سائق جديد",
    "personalInformation": "المعلومات الشخصية",
    "fullName": "الاسم الكامل",
    "enterFullName": "أدخل الاسم الكامل",
    "emailAddress": "عنوان البريد الإلكتروني",
    "phoneNumber": "رقم الهاتف",
    "address": "العنوان",
    "enterHomeAddress": "أدخل عنوان المنزل",
    "workInformation": "معلومات العمل",
    "driversLicenseNumber": "رقم رخصة القيادة",
    "assignedVehicle": "المركبة المخصصة",
    "selectVehicle": "اختر مركبة",
    "emergencyContact": "جهة الاتصال في حالات الطوارئ",
    "nameAndPhone": "الاسم ورقم الهاتف",
    "initialStatus": "الحالة الأولية",
    "addingDriver": "جاري إضافة السائق...",
    "addDriver": "إضافة سائق",
    "cancel": "إلغاء",
    "required": "مطلوب",
    "nameRequired": "الاسم مطلوب",
    "emailRequired": "البريد الإلكتروني مطلوب",
    "invalidEmail": "تنسيق البريد الإلكتروني غير صحيح",
    "phoneRequired": "رقم الهاتف مطلوب",
    "licenseRequired": "رقم رخصة القيادة مطلوب",
    "vehicleRequired": "تعيين المركبة مطلوب",
    "idImageRequired": "صورة الهوية الرسمية مطلوبة",
    "coverageRequired": "منطقة تغطية واحدة على الأقل مطلوبة",
    "ensureAccuracy": "يرجى التأكد من دقة جميع المعلومات المطلوبة. سيحصل السائق على بيانات تسجيل الدخول عبر البريد الإلكتروني بعد التسجيل.",

    // Visit Management
    visitManagement: "إدارة الزيارات",
    monitorDelegateVisits: "مراقبة وإدارة زيارات المندوبين",
    scheduleVisit: "جدولة زيارة",
    createNewVisit: "إنشاء زيارة جديدة للمندوب",
    delegate: "المندوب",
    selectDelegate: "اختر المندوب",
    customerName: "اسم العميل",
    enterCustomerName: "أدخل اسم العميل",
    customerAddress: "عنوان العميل",
    enterCustomerAddress: "أدخل عنوان العميل",
    visitType: "نوع الزيارة",
    delivery: "توصيل",
    pickup: "استلام",
    inspection: "فحص",
    maintenance: "صيانة",
    meeting: "اجتماع",
    priority: "الأولوية",
    low: "منخفض",
    medium: "متوسط",
    high: "عالي",
    urgent: "عاجل",
    duration: "المدة (بالدقائق)",
    startTime: "وقت البداية",
    endTime: "وقت النهاية",
    notes: "ملاحظات",
    additionalNotes: "ملاحظات إضافية لهذه الزيارة",
    visitDetails: "تفاصيل الزيارة",
    scheduledStart: "البداية المجدولة",
    scheduledEnd: "النهاية المجدولة",
    allowedDuration: "المدة المسموحة",
    viewDetails: "عرض التفاصيل",
    activeAlerts: "التنبيهات النشطة",
    visitAlerts: "تنبيهات الزيارات",
    noVisitAlerts: "لا توجد تنبيهات زيارات",
    allVisitsOnSchedule: "جميع الزيارات في الموعد المحدد وضمن الحدود الزمنية.",
    markAsRead: "تعيين كمقروء",
    lateVisitAlert: "تنبيه زيارة متأخرة",
    timeExceededAlert: "تنبيه تجاوز الوقت",
    noShowAlert: "تنبيه عدم الحضور",
    earlyCompletionAlert: "تنبيه إكمال مبكر",
    visitId: "معرف الزيارة",
    delegateId: "معرف المندوب",
    lateArrival: "وصول متأخر",
    timeExceeded: "تجاوز الوقت",
    noShow: "عدم الحضور",
    earlyCompletion: "إكمال مبكر",
    critical: "حرج",
    warning: "تحذير",
    info: "معلومات",
    success: "نجح",
    resolved: "تم الحل",
    resolve: "حل",

    // Internal Messaging
    internalMessaging: "الرسائل الداخلية",
    communicateWithStaff: "التواصل مع الموظفين واستخدام روبوت المحادثة",
    composeMessage: "كتابة رسالة",
    sendMessageToStaff: "إرسال رسالة إلى موظف",
    recipient: "المستقبل",
    selectRecipient: "اختر المستقبل",
    subject: "الموضوع",
    enterMessageSubject: "أدخل موضوع الرسالة",
    message: "الرسالة",
    enterYourMessage: "أدخل رسالتك",
    sendMessage: "إرسال الرسالة",
    messages: "الرسائل",
    searchMessages: "البحث في الرسائل...",
    from: "من",
    to: "إلى",
    sent: "تم الإرسال",
    new: "جديد",
    unread: "غير مقروء",
    noUnreadMessages: "لا توجد رسائل غير مقروءة",
    chatBot: "روبوت المحادثة",
    askQuestionsAboutVisits: "اسأل أسئلة حول الزيارات أو المندوبين أو معلومات النظام",
    typeYourMessage: "اكتب رسالتك...",
    askMeAnything: "اسألني أي شيء...",
    todaysVisits: "زيارات اليوم",
    activeAlerts: "التنبيهات النشطة",
    delegateStatus: "حالة المندوب",
    deliveryInfo: "معلومات التوصيل",
    internalChatBot: "روبوت المحادثة الداخلي",
    online: "متصل",
    aiAssistant: "مساعد ذكي",
    welcomeToAssistant: "مرحباً بك في مساعد شركة الرفيدان للصناعة. يمكنني مساعدتك في:",
    visitSchedules: "جداول الزيارات ومعلومات المندوبين",
    systemAlerts: "تنبيهات النظام والإشعارات",
    deliveryTracking: "تتبع التوصيل وتحديثات الحالة",
    companyInformation: "معلومات الشركة العامة",
    howCanIAssist: "كيف يمكنني مساعدتك اليوم؟",
    quickActions: "الإجراءات السريعة",

    // Chatbot Responses
    chatbotResponses: {
      visitInfo: "يمكنني مساعدتك في معلومات الزيارات! إليك ما وجدته:",
      todaysVisits: "زيارات اليوم:",
      delegateStatus: "إليك حالة المندوب الحالية:",
      activeDelegates: "المندوبون النشطون:",
      allDelegatesActive: "جميع المندوبين نشطون حالياً ومستعدون للمهام.",
      currentAlerts: "التنبيهات الحالية:",
      deliveryStatus: "حالة التوصيل:",
      inTransit: "في الطريق",
      completedToday: "مكتمل اليوم",
      scheduled: "مجدول",
      averageDeliveryTime: "متوسط وقت التوصيل",
      onTimeDeliveryRate: "معدل التوصيل في الوقت المحدد",
      fleetStatus: "حالة الأسطول:",
      activeVehicles: "المركبات النشطة",
      inMaintenance: "في الصيانة",
      fuelLevel: "مستوى الوقود",
      maintenanceAlerts: "تنبيهات الصيانة:",
      timeManagement: "إدارة الوقت:",
      currentTime: "الوقت الحالي",
      lateVisits: "الزيارات المتأخرة",
      exceededTime: "تجاوز الوقت",
      locationInformation: "معلومات الموقع:",
      activeZones: "المناطق النشطة",
      coverageAreas: "مناطق التغطية",
      currentOperations: "العمليات الحالية",
      greeting: "مرحباً! مرحباً بك في مساعد شركة الرفيدان للصناعة. أنا هنا لمساعدتك في:",
      helpTopics: "أنا هنا للمساعدة! إليك بعض الأشياء التي يمكنك سؤالي عنها:",
      visitManagement: "إدارة الزيارات:",
      delegateInformation: "معلومات المندوب:",
      systemAlerts: "تنبيهات النظام:",
      deliveryTracking: "تتبع التوصيل:",
      justAsk: "فقط اسألني أي شيء!",
      defaultResponse: "أفهم أنك تسأل عن:",
      beMoreSpecific: "يمكنني مساعدتك في إدارة الزيارات وتتبع المندوبين وتنبيهات النظام ومعلومات التوصيل وحالة أسطول المركبات. هل يمكنك أن تكون أكثر تحديداً حول ما تحتاجه؟",
      tryAsking: "جرب السؤال:",
      showTodaysVisits: "أظهر لي زيارات اليوم",
      anyAlerts: "أي تنبيهات؟",
      delegateStatus: "حالة المندوب",
      deliveryInformation: "معلومات التوصيل"
    },

    // After-Sales Support
    afterSalesSupport: "دعم ما بعد البيع",
    manageCustomerSupport: "إدارة استفسارات العملاء والشكاوى والصيانة والضمانات",
    newSupportCase: "حالة دعم جديدة",
    customerInquiries: "استفسارات العملاء",
    complaints: "الشكاوى",
    maintenanceRequests: "طلبات الصيانة",
    warrantyManagement: "إدارة الضمانات",
    followUpServices: "خدمات المتابعة",
    totalInquiries: "إجمالي الاستفسارات",
    resolvedInquiries: "الاستفسارات المحلولة",
    activeComplaints: "الشكاوى النشطة",
    escalationRate: "معدل التصعيد",
    customerSatisfaction: "رضا العملاء",
    averageRating: "التقييم المتوسط",
    warrantyOverview: "نظرة عامة على الضمانات",
    activeWarranties: "الضمانات النشطة",
    warrantyClaims: "مطالبات الضمان",
    approvalRate: "معدل الموافقة",
    performanceMetrics: "مقاييس الأداء",
    avgResolutionTime: "متوسط وقت الحل",
    avgMaintenanceCost: "متوسط تكلفة الصيانة",
    customerRetention: "الاحتفاظ بالعملاء",
    scheduled: "مجدول",
    completed: "مكتمل",
    completionRate: "معدل الإكمال",
    searchInquiries: "البحث في الاستفسارات...",
    searchComplaints: "البحث في الشكاوى...",
    searchMaintenance: "البحث في الصيانة...",
    searchWarranties: "البحث في الضمانات...",
    searchFollowUps: "البحث في المتابعات...",
    general: "عام",
    technical: "تقني",
    billing: "فوترة",
    warranty: "ضمان",
    complaint: "شكوى",
    maintenance: "صيانة",
    productQuality: "جودة المنتج",
    deliveryIssue: "مشكلة التوصيل",
    serviceQuality: "جودة الخدمة",
    billingError: "خطأ في الفوترة",
    communication: "التواصل",
    other: "أخرى",
    investigating: "قيد التحقيق",
    escalated: "متصعد",
    preventive: "وقائي",
    corrective: "تصحيحي",
    emergency: "طوارئ",
    upgrade: "ترقية",
    requested: "مطلوب",
    cancelled: "ملغي",
    standard: "قياسي",
    extended: "ممتد",
    premium: "مميز",
    expired: "منتهي الصلاحية",
    void: "باطل",
    transferred: "منقول",
    submitted: "مقدم",
    underReview: "قيد المراجعة",
    approved: "موافق عليه",
    rejected: "مرفوض",
    rescheduled: "معاد جدولته",
    satisfactionSurvey: "استطلاع الرضا",
    productTraining: "تدريب المنتج",
    maintenanceReminder: "تذكير الصيانة",
    upgradeOffer: "عرض الترقية",
    feedbackCollection: "جمع التعليقات",
    equipmentMaintenance: "صيانة المعدات",
    warrantyCovered: "مشمول بالضمان",
    claims: "مطالبات",
    expires: "ينتهي",
    months: "أشهر",
    level: "مستوى",
    technician: "فني",
    nextFollowUp: "المتابعة التالية",
    assignedTo: "معين لـ",

    // Visits
    uploadTasks: "تحميل المهام",
    filterByDelegate: "تصفية حسب المندوب",
    filterByRegion: "تصفية حسب المنطقة",
    filterByCustomer: "تصفية حسب العميل",
    filterByDate: "تصفية حسب التاريخ",
    status: "الحالة",
    pending: "معلق",
    completed: "مكتمل",
    missed: "مفقود",

    assistantTitle: "مساعد الرفيدان",
    hello: "مرحباً",
    send: "إرسال",
    minimize: "تصغير",
    maximize: "فتح المساعد",
    provideFeedback: "أرسل ملاحظاتك",
    feedbackThanks: "شكراً لملاحظاتك!",
    helpful: "مفيد",
    notHelpful: "غير مفيد",
    optionalComment: "تعليق اختياري",
    submit: "إرسال"
  },
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("en")
  const [isClient, setIsClient] = useState(false)

  useEffect(() => {
    setIsClient(true)
    // Check for saved language only on client side
    const savedLang = localStorage.getItem("language") as Language
    if (savedLang && (savedLang === "en" || savedLang === "ar")) {
      setLanguage(savedLang)
    }
  }, [])

  useEffect(() => {
    if (isClient) {
      localStorage.setItem("language", language)
      document.documentElement.lang = language
      document.documentElement.dir = language === "ar" ? "rtl" : "ltr"
    }
  }, [language, isClient])

  const t = (key: string): string => {
    return translations[language][key as keyof (typeof translations)[typeof language]] || key
  }

  const isRTL = language === "ar"

  return <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
